### ISSUE TITLE
Signals: 24h format instead of 12h format

### ISSUE THREAD

**Issue by ProfMertes** [florensh/locating-web-frontend#1]
Wegen der Übersichtlichkeit, auch beim Suchen und Eingrenzen von Zeiträumen

**Comment by florensh** [comment]
siehe https://docs.angularjs.org/api/ng/filter/date

anpassen in signals.html:93

**Comment by ProfMertes** [comment]
Done with [this commit](https://github.com/florensh/locating-web-frontend/commit/8979420490f6b10210fb05d1005c7252943ff46e)
